# Generated by Django 3.2.8 on 2021-12-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
